CREATE TABLE `analyses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`searchTerm` varchar(255) NOT NULL,
	`productTitle` text NOT NULL,
	`productPlatform` varchar(50) NOT NULL,
	`priceUsd` int NOT NULL,
	`productRating` int NOT NULL,
	`productImage` text,
	`exchangeRate` int NOT NULL,
	`priceBrl` int NOT NULL,
	`importTax` int NOT NULL,
	`iof` int NOT NULL,
	`shippingCost` int NOT NULL,
	`totalCost` int NOT NULL,
	`avgPriceBr` int NOT NULL,
	`minPriceBr` int NOT NULL,
	`maxPriceBr` int NOT NULL,
	`totalSellers` int NOT NULL,
	`competitionLevel` varchar(20) NOT NULL,
	`avgRatingBr` int NOT NULL,
	`profitMargin` int NOT NULL,
	`opportunityScore` int NOT NULL,
	`isViable` int NOT NULL,
	`recommendation` varchar(100) NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `analyses_id` PRIMARY KEY(`id`)
);
