CREATE TABLE `quotationItems` (
	`id` int AUTO_INCREMENT NOT NULL,
	`quotationId` int NOT NULL,
	`description` text NOT NULL,
	`ncmCode` varchar(10) NOT NULL,
	`quantity` int NOT NULL,
	`unitPriceFob` int NOT NULL,
	`totalPriceFob` int NOT NULL,
	`grossWeight` int,
	`netWeight` int,
	`volume` int,
	`iiRate` int NOT NULL,
	`ipiRate` int NOT NULL,
	`pisRate` int NOT NULL,
	`cofinsRate` int NOT NULL,
	`icmsRate` int NOT NULL,
	`customsValue` int NOT NULL,
	`iiAmount` int NOT NULL,
	`ipiAmount` int NOT NULL,
	`pisAmount` int NOT NULL,
	`cofinsAmount` int NOT NULL,
	`icmsAmount` int NOT NULL,
	`landedCostPerUnit` int NOT NULL,
	`landedCostTotal` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `quotationItems_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `quotations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`quotationName` varchar(255) NOT NULL,
	`incoterm` varchar(10) NOT NULL,
	`transportType` varchar(20) NOT NULL,
	`currency` varchar(3) NOT NULL DEFAULT 'USD',
	`exchangeRate` int NOT NULL,
	`invoiceUrl` text,
	`packListUrl` text,
	`internationalFreight` int NOT NULL DEFAULT 0,
	`insurance` int NOT NULL DEFAULT 0,
	`storage` int NOT NULL DEFAULT 0,
	`portFees` int NOT NULL DEFAULT 0,
	`customsBrokerFees` int NOT NULL DEFAULT 0,
	`certifications` int NOT NULL DEFAULT 0,
	`totalFob` int NOT NULL,
	`totalCustomsValue` int NOT NULL,
	`totalII` int NOT NULL,
	`totalIPI` int NOT NULL,
	`totalPIS` int NOT NULL,
	`totalCofins` int NOT NULL,
	`totalICMS` int NOT NULL,
	`totalLandedCost` int NOT NULL,
	`status` enum('draft','completed','archived') NOT NULL DEFAULT 'draft',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `quotations_id` PRIMARY KEY(`id`)
);
